### ISSUE TITLE
Search not working (again) when nested property is null

### ISSUE THREAD

**Issue by timbze** [gustavnavar/Grid.Blazor#138] opened 2020-03-19 22:53 UTC
**Describe the bug**
It seems like the same issue came up again that we had here: https://github.com/gustavnavar/Grid.Blazor/issues/93

I am using the latest GridBlazor available in nuget.

I did not do any testing with the source yet now to see what changed.

The issue is, my grid has a column with truck.person.full_name, and if any value in that column is null then search does nothing.

**Comment by gustavnavar** [comment] 2020-03-20 10:43
The 2 classes that were modified to fix issue https://github.com/gustavnavar/Grid.Blazor/issues/93 have not been changed since then.

I will try to reproduce this issue.

**Comment by gustavnavar** [comment] 2020-03-20 15:17
GridBlazor 1.3.32 should work for you

**Comment by timbze** [comment] 2020-03-20 15:48
Still not working. GridBlazor is throwing NullReferenceException at L208 (`value = _constraint(instance);`) in GridColumn.cs

**Comment by gustavnavar** [comment] 2020-03-20 15:56
The code  in  GridColumn.cs is:

```c#
                    TDataType value = default(TDataType);

                    var nullReferece = false;
                    try
                    {
                        value = _constraint(instance);
                    }
                    catch (NullReferenceException)
                    {
                        nullReferece = true;
                        // specified expression throws NullReferenceException
                        // example: x=>x.Child.Property, when Child is NULL
                    }

                    if (nullReferece || value == null)
                        textValue = string.Empty;
                    else
                        textValue = GetFormatedValue(value);
```

So, in case of a null object the text on the cell is ```string.Empty```.

**Comment by gustavnavar** [comment] 2020-03-20 16:04
The error should be in some other place. 

By the way I could reproduce the error with the following code using GridBlazor 1.3.31:
- blazor page
```c#
@page "/trucks"
@using GridBlazorServerSide.Resources
@using GridBlazorServerSide.Services
@using Microsoft.Extensions.Primitives
@using System.Globalization
@using System.Threading.Tasks
@inject ITruckService truckService

@if (_task.IsCompleted)
{
    <div class="row">
        <div class="col-md-12">
            <GridComponent T="Truck" Grid="@_grid"></GridComponent>
        </div>
    </div>
}
else
{
    <p><em>Loading...</em></p>
}

@code
{
    private CGrid<Truck> _grid;
    private Task _task;

    protected override async Task OnParametersSetAsync()
    {
        var locale = CultureInfo.CurrentCulture;
        SharedResource.Culture = locale;

        Action<IGridColumnCollection<Truck>> columns = c =>
        {
            c.Add(t => t.description)
                .Titled("Description")
                .Filterable(true);

            c.Add(t => t.owner_person.full_name)
                .Titled("Owner")
                .Filterable(true);
        };

        var query = new QueryDictionary<StringValues>();
        var client = new GridClient<Truck>(q => truckService.GetTrucksGridRows(columns, q),
            query, false, "trucksGrid", columns, locale)
            .Sortable()
            .Filterable()
            .ClearFiltersButton(true)
            .SetStriped(true)
            .WithMultipleFilters()
            .WithGridItemsCount()
            .Searchable(true, false, false);

        _grid = client.Grid;
        // Set new items to grid
        _task = client.UpdateGrid();
        await _task;
    }
}
```
- service:
```c#
using GridMvc.Server;
using GridShared;
using GridShared.Utility;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Primitives;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace GridBlazorServerSide.Services
{
    public class TruckService : ITruckService
    {
        public ItemsDTO<Truck> GetTrucksGridRows(Action<IGridColumnCollection<Truck>> columns,
            QueryDictionary<StringValues> query)
        {
            var server = new GridServer<Truck>(GetAll(), new QueryCollection(query),
                    true, "trucksGrid", columns)
                        .Sortable()
                        .WithPaging(10)
                        .Filterable()
                        .WithMultipleFilters()
                        .Groupable(true)
                        .Searchable(true, false, false);

            // return items to displays
            var items = server.ItemsToDisplay;
            return items;
        }

        private IEnumerable<Truck> GetAll()
        {
            var trucks = new List<Truck>();
            trucks.Add(new Truck {
                truck_id = 1,
                description = "Truck 1",
                owner_person = new Person {
                    person_id = 1,
                    first_name = "Owner",
                    last_name = "1"
                }
            });
            trucks.Add(new Truck
            {
                truck_id = 2,
                description = "Truck 2",
                owner_person = new Person
                {
                    person_id = 2,
                    last_name = "2"
                }
            });
            trucks.Add(new Truck
            {
                truck_id = 3,
                description = "Truck 3",
                owner_person = new Person
                {
                    person_id = 1,
                    first_name = "Owner"
                }
            });
            trucks.Add(new Truck
            {
                truck_id = 4,
                description = "Truck 4",
                owner_person = new Person
                {
                    first_name = "Owner",
                    last_name = "4"
                }
            });
            trucks.Add(new Truck
            {
                truck_id = 5,
                description = "Truck 5"
            });
            trucks.Add(new Truck
            {
                description = "Truck 6",
                owner_person = new Person
                {
                    person_id = 6,
                    first_name = "Owner",
                    last_name = "6"
                }
            });
            return trucks;
        }
    }

    [Serializable]
    public class Truck
    {
        [Key]
        public int? truck_id { get; set; }
        public string description { get; set; }
        public Person owner_person { get; set; }
    }

    [Serializable]
    public class Person
    {
        [Key]
        public int? person_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string full_name => $"{ first_name } { last_name }";
    }

    public interface ITruckService
    {
        ItemsDTO<Truck> GetTrucksGridRows(Action<IGridColumnCollection<Truck>> columns,
            QueryDictionary<StringValues> query);
    }
}
```

If I used these model definition:
```c#
    public Person owner_person { get; set; } = new Person();
```
even with GridBlazor 1.3.31 there was no error.

As soon as I removed the creation of a ```Person``` instance in the ```owner_person``` definition searching and filtering stop working as expected. 

This was the error fixed on version 1.3.32

**Comment by timbze** [comment] 2020-03-20 16:06
For some reason Visual Studio was stopping me there even though there is a try...catch. After trying again it started working now, so not sure why it was temporarily not working yet even after upgrading GridBlazor. Maybe nuget was the issue at this point.

Everything is working again.

Thanks for your help and great work on this project!

**Closed** 2020-03-20 17:51 UTC

**Comment by gustavnavar** [comment] 2020-03-20 21:14
I've just realized that version 1.3.32 has a bug filtering DateTime columns. I've deprecate it on Nuget.org.

Please, download version 1.3.33 and check that works ok for you.

**Comment by timbze** [comment] 2020-03-24 12:17
> Please, download version 1.3.33 and check that works ok for you.

Yes, still works
