### ISSUE TITLE
Checkbox column click should trigger  onchange event 

### ISSUE THREAD

**Issue by prabhakarreddy1234** [gustavnavar/Grid.Blazor#158] opened 2020-05-05 01:56 UTC
I have added a `checkbox` column to the grid as below. I can't figure out a way to capture the event when that checkbox is checked or unchecked. 

 c.Add("CheckboxColumn").Titled("Active").SetCheckboxColumn(true, o => o.IsActive).SetWidth("5%");

I tried adding a custom component with checkbox in it and rendered as component. It works but it's very slow. Everytime the grid state changes then all the checkbox components needs to be bounded again. So UI is pretty much unresponsive.

Suggest me any other solution to capture grid checkbox changed event.

**Comment by gustavnavar** [comment] 2020-05-05 16:03
The checkbox changed events are currenlty internal. 

You can access the value of the checkboxes using the ```CheckedRows``` property of the ```GridComponent``` object

**Comment by prabhakarreddy1234** [comment] 2020-05-05 16:10
Thanks @gustavnavar . Yes, i'm accessing `CheckedRows` in other parts of the app. But I need to show a modal dialog on click of each checkbox and i don't think there is a way to achieve it as of now.

Is there a way the `checked` event can be exposed in the next releases ?

**Comment by gustavnavar** [comment] 2020-05-05 16:21
I will make public the ```HeaderCheckboxChanged``` and ```RowCheckboxChanged``` events of the ```GridComponent``` object on the next version of the package

**Comment by prabhakarreddy1234** [comment] 2020-05-05 16:32
Great.

Also if possible expose a parameter to SetCheckBoxColumn method which decides whether a `Header` checkbox is to be shown or not. Sometimes we don't need header checkbox at all.

**Comment by gustavnavar** [comment] 2020-05-05 16:40
If you don't want to show the header checkbox you should define the column as follows:
```c#
c.Add("CheckboxColumn").SetCheckboxColumn(false, o => o.IsActive);
```

**Comment by gustavnavar** [comment] 2020-05-05 16:47
I will update the documentation because the parameters for ```SetCheckboxColumn``` were misleading

**Comment by gustavnavar** [comment] 2020-05-05 20:54
The package GridBlazor 1.5.3 has public checkbox events.

**Comment by prabhakarreddy1234** [comment] 2020-05-06 11:16
Thanks. I see them now. But RowCheckboxChanged event is passing only `CheckboxEventArgs` which is just giving the column name and "checked" or "unchecked" string as value. 

Is it possible to pass the selected row as parameter on this event ? I guess i'm looking at similar behaviour as  `OnRowClicked` event.

**Comment by gustavnavar** [comment] 2020-05-07 00:02
The package GridBlazor 1.5.4 has 2 additional properties for RowCheckboxChanged  event:
- Item
- RowId

**Comment by prabhakarreddy1234** [comment] 2020-05-08 16:46
Thanks. Now i can see the required data in the event. But i observed that `RowCheckboxChanged` event is being fired while grid is rendering for every checkbox which has true value. 
Am i registering the event in the wrong place?
```
protected override void OnAfterRender(bool firstRender)
    {
        if (!firstRender && _gridComponent != null)
        {
            _gridComponent.RowCheckboxChanged += CheckChanged;
        }
    }
```

**Comment by timbze** [comment] 2020-05-11 14:26
> And on `firstRender` `_gridComponent` is null.

You could try to run StateHasChanged() after calling client.UpdateGrid() and see if that would fix your null issue. That is, assuming you are inializing your grid in OnInititializedAsync...

**Comment by prabhakarreddy1234** [comment] 2020-05-16 13:20
Added `StateHasChanged()` after `client.UpdateGrid()`  in `OnInitializedAsync`.

But still `_gridComponent` is null on `firstRender`.

```
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            _gridComponent.RowCheckboxChanged += CheckChanged;
        }
        await Task.CompletedTask;
    }
```

**Comment by prabhakarreddy1234** [comment] 2020-05-19 20:47
Any workaround to make it work?

**Comment by gustavnavar** [comment] 2020-05-26 16:32
Can you share the full code of the blazor page?

**Comment by gustavnavar** [comment] 2020-05-27 22:07
You  can try the following code:

```c#
@code
{
   private bool _areEventsLoaded = false;

   ....
   protected override void OnAfterRender(bool firstRender)
    {
        if (!_areEventsLoaded && _gridComponent != null)
        {
             _gridComponent.RowCheckboxChanged += CheckChanged;
            _areEventsLoaded = true;
        }
    }
}
```

**Comment by prabhakarreddy1234** [comment] 2020-05-28 23:01
Thanks. I tried it but no luck. I see that `onload` and `on any checkbox checked/unchecked` the last row `CheckboxChanged` is firing always. So for e.g if i tick 3rd row check box then `CheckboxChanged` event is firing twice. Once for 3rd row checkbox and 2nd for last row checkbox.

```
Action<IGridColumnCollection<Person>> columns = c =>
        {
            c.Add("CheckboxColumn").Titled("Active").SetCheckboxColumn(false, o => o.IsActive).SetWidth("5%");
            c.Add(o => o.Id).Titled("Id").Sortable(true).SetWidth("15%");
            c.Add(o => o.Name);
            c.Add(o => o.Position);
            c.Add(o => o.Level);
            c.Add(o => o.Age).Titled("Age");
            c.Add(o => o.Location).Titled("Location");
        };

        var query = new QueryDictionary<StringValues>();

        var client = new GridClient<Person>(async query => await Service.Get(Id, query, columns), query, false, "SampleGrid", columns)
            .SetStriped(true)
            .Sortable(true)
            .Filterable(true)
            .SetExcelExport(true)
            .ClearFiltersButton(true);

        _grid = client.Grid;

        // Set new items to grid
        _task = client.UpdateGrid();
        await _task;
```

**Comment by prabhakarreddy1234** [comment] 2020-06-12 20:28
@gustavnavar  Any update on this issue.

**Comment by gustavnavar** [comment] 2020-06-12 21:30
I would need the full code of the blazor page, the ```Person``` model and the service to retrieve the grid data to understand the reason why ```GridComponent``` is null. Can you upload these classes?

**Comment by gustavnavar** [comment] 2020-07-02 22:38
I close this issue. If you required further investigation you should send a sample project to be able reproduce the issue.

**Closed by gustavnavar** 2020-07-02 22:38 UTC
